# Site-wide settings
# ------------------
title: Home
email: ignaciofs.dataresearch@gmail.com
description: Ignacio Jiménez - Portfolio

minima:
  hide_site_feed_link: true
  nav_pages:
    - about.md

# Build settings
# --------------
theme: minima
