# Site-wide settings
# ------------------
title: Ignacio Jiménez
email: ignaciofs.dataresearch@gmail.com
description: Junior Data Analyst.

minima:
  hide_site_feed_link: true

# Build settings
# --------------
theme: minima
